name: Build Plugin

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  run:
    name: Run action
    runs-on: ubuntu-latest
    permissions:
      contents: write

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup SourcePawn Compiler
      uses: rumblefrog/setup-sp@master
      with:
        version: "1.12.x"

    - name: Compile plugin
      run: |
        spcomp -i"./addons/sourcemod/scripting/include/" addons/sourcemod/scripting/mge.sp -o ./addons/sourcemod/plugins/mge.smx

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        name: Latest Build
        files: ./addons/sourcemod/plugins/mge.smx
        fail_on_unmatched_files: true
        generate_release_notes: false
        prerelease: false
